const storage = {
  users: [{
    id: 2,
    email: 'johndoe@example.com',
    firstName: 'John',
    lastName: 'Doe',
    password: '$2b$10$QiYF8euLqXzz2/rHIC2YK.CzBUYTWMzq3SA11h5EHENSc2YEkRLfO',
    address: 'Lagos',
    isAdmin: false,
  },
  {
    id: 584,
    email: 'kuzko584@gmail.com',
    firstName: 'Chisom',
    lastName: 'Amaechi',
    password: 'mypassword',
    address: 'Lagos',
    isAdmin: true,
  }],
  adverts: [{
    id: 1,
    owner: 2,
    created_on: '',
    condition: 'New',
    status: 'available',
    price: 13700000,
    brand: 'Toyota',
    model: 'Avalon',
    body_type: 'Sedan',

  },
  {
    id: 2,
    owner: 1,
    created_on: '',
    condition: 'New',
    status: 'available',
    price: 13700000,
    brand: 'Toyota',
    model: 'Avalon',
    body_type: 'Sedan',

  },
  {
    id: 3,
    owner: 1,
    created_on: '',
    condition: 'New',
    status: 'available',
    price: 10200000,
    brand: 'Toyota',
    model: 'Camry',
    body_type: 'Sedan',

  }],
  orders: [{
    created_on: '',
    id: 4,
    buyer: 2,
    carId: 1,
    price: 13700000,
    price_offer: 11000000,
    status: 'pending',
  },
  {
    created_on: '',
    id: 5,
    buyer: 2,
    carId: 1,
    price: 13700000,
    price_offer: 11000000,
    status: 'rejeted',
  }],
  flags: [{
    id: 1,
    carId: 1,
    created_on: '',
    reason: 'fraudulent',
    description: 'String',
  }],
};

export default storage;
